[package]
name = "dorfconf"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.102"
facet = "0.46.5"
facet-json = "0.46.1"

[dependencies.rust-uci]
git = "https://github.com/ffddorf/rust-uci"
rev = "9c9bcd55ecefc270d831983b1fdbb1489aceba81"
# path = "../../rust-uci/rust-uci"

[features]
vendor-uci = ["rust-uci/vendored"]
ide-defaults = ["vendor-uci"]
